import pandas as pd

df = pd.read_csv("laptop_price - dataset.csv")
print("For inches,")
print("Mean: ", df['Inches'].mean(), "\nMedian: ", df['Inches'].median())
print("Mode: ", df['Inches'].mode()[0], "\nVariance: ", df['Inches'].var())
print("Standard deviation: ", df['Inches'].std())
print()
print("For CPU_Frequency (GHz),")
print("Mean: ", df['CPU_Frequency (GHz)'].mean(), "\nMedian: ", df['CPU_Frequency (GHz)'].median())
print("Mode: ", df['CPU_Frequency (GHz)'].mode()[0], "\nVariance: ", df['CPU_Frequency (GHz)'].var())
print("Standard deviation: ", df['CPU_Frequency (GHz)'].std())
print()
print("For RAM,")
print("Mean: ", df['RAM (GB)'].mean(), "\nMedian: ", df['RAM (GB)'].median())
print("Mode: ", df['RAM (GB)'].mode()[0], "\nVariance: ", df['RAM (GB)'].var())
print("Standard deviation: ", df['RAM (GB)'].std())
print()
print("For Weight (kg),")
print("Mean: ", df['Weight (kg)'].mean(), "\nMedian: ", df['Weight (kg)'].median())
print("Mode: ", df['Weight (kg)'].mode()[0], "\nVariance: ", df['Weight (kg)'].var())
print("Standard deviation: ", df['Weight (kg)'].std())
print()
print("For Price (Euro),")
print("Mean: ", df['Price (Euro)'].mean(), "\nMedian: ", df['Price (Euro)'].median())
print("Mode: ", df['Price (Euro)'].mode()[0], "\nVariance: ", df['Price (Euro)'].var())
print("Standard deviation: ", df['Price (Euro)'].std())
print()